version: '3.8'

services:
  postgres-library:
    image: postgres:latest
    container_name: library-postgres
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - postgres_library_data:/var/lib/postgresql
      
  postgres-reports:
    image: postgres:latest
    container_name: reports-postgres
    environment:
      POSTGRES_DB: reports
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres_reports_data:/var/lib/postgresql
  
  postgres-hangfire:
    image: postgres:latest
    container_name: hangfire-postgres
    environment:
      POSTGRES_DB: jobs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5439:5432"
    volumes:
      - postgres_hangfire_data:/var/lib/postgresql
      
  minio:
    image: minio/minio
    container_name: library-minio
    ports:
      - "9003:9000"
      - "9004:9001"
    environment:
      MINIO_ROOT_USER: RJYwhPEf7O1DbRu5SvtF
      MINIO_ROOT_PASSWORD: tLRHkGHBm105Nn8zGwVEEHmmGAchxkcbvINe7wjw
    volumes:
      - minio_data:/data
    command: server  /data --console-address ":9001"
    
  redis:
    image: redis:latest
    container_name: library-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  
  rabbitmq:
    image: rabbitmq:4-management
    container_name: library-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  
  smtp4dev:
    image: rnwood/smtp4dev:latest
    container_name: smtp4dev
    restart: unless-stopped
    ports:
      - "3000:80"   
      - "25:25"      
    volumes:
      - smtp4dev-data:/app/data
    environment:
      - LOG_LEVEL=Info
      - API_ENABLED=true
      
volumes:
  postgres_library_data:
    driver: local
  postgres_reports_data:
    driver: local
  postgres_hangfire_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
  rabbitmq_data:
    driver: local
  smtp4dev-data:
    driver: local