version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: books-postgres
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: books-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
      
  minio:
    image: minio/minio
    container_name: books-minio
    ports:
      - "9003:9000"
      - "9004:9001"
    environment:
      MINIO_ROOT_USER: RJYwhPEf7O1DbRu5SvtF
      MINIO_ROOT_PASSWORD: tLRHkGHBm105Nn8zGwVEEHmmGAchxkcbvINe7wjw
    volumes:
      - minio_data:/data
    command: server  /data --console-address ":9001"
      
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local