<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-PracticalWork.Library.BackgroundTasks-8abc44f0-4a24-42f0-983c-139901efc18e</UserSecretsId>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Cache.Redis" />
        <PackageReference Include="Data.Minio" />
        <PackageReference Include="Hangfire" />
        <PackageReference Include="Hangfire.PostgreSql" />
        <PackageReference Include="MessageBroker" />
        <PackageReference Include="Microsoft.Extensions.Hosting"/>
    </ItemGroup>
    <ItemGroup>
        <None Update="HtmlTemplates\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\PracticalWork.Library.Application\PracticalWork.Library.Application.csproj" />
      <ProjectReference Include="..\PracticalWork.Library.Data.PostgreSql\PracticalWork.Library.Data.PostgreSql.csproj" />
      <ProjectReference Include="..\PracticalWork.Library.Email\PracticalWork.Library.Email.csproj" />
      <ProjectReference Include="..\PracticalWork.Library\PracticalWork.Library.csproj" />
    </ItemGroup>
</Project>
