<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="v1\Reports\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Contracts" />
      <PackageReference Include="Domain" />
    </ItemGroup>

</Project>
